# Generated by Django 6.0.6 on 2026-06-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatasAx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('cookie', models.TextField(blank=True, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('url_completa', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Data Ax',
                'verbose_name_plural': 'Data Axs',
                'ordering': ['-fecha'],
            },
        ),
    ]
